### ISSUE TITLE
forge 1.20.1 eldritch end crashes 

### ISSUE THREAD

**Issue by jojofenin99** [nvb-uy/Eldritch_End#13]
here are the logs and debug logs:

[debug-2.log](https://github.com/nvb-uy/Eldritch_End/files/14089180/debug-2.log)
[2024-01-29-10.log](https://github.com/nvb-uy/Eldritch_End/files/14089182/2024-01-29-10.log)

**Comment by nvb-uy** [comment]
From a quick look, your issue seems to be here:

```
[14:51:47] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'citadel', Requested by: 'iceandfire', Expected range: '[2.4.1,2.4.99]', Actual version: '2.5.2'
	Mod ID: 'cerbons_api', Requested by: 'bosses_of_mass_destruction', Expected range: '[,1.1.0)', Actual version: '1.1.0'
```

**Comment by nvb-uy** [comment]
Are you sure it's eldritch end? Have you removed the mod and see if it loads? Because from those logs it only mentions those 2 dependencies having the wrong version, and in the debug log the mention of a EE mixin not using the callbackinfo is something normal that shouldn't really affect at all the functionality of the game.

**Comment by nvb-uy** [comment]
Closing as there's no response
